persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 10Gi

datasources:
 datasources.yaml:
   apiVersion: 1
   datasources:
   - name: Prometheus
     type: prometheus
     url: http://prometheus-server/prometheus/
     access: proxy
     isDefault: true

dashboards:
    default:
      kube-prometheus-dashboard:
        file: dashboards/kubernetes-prometheus-dashboard.json
      kubernetes-rchakra3-dashboard:
        file: dashboards/kubernetes-rchakra3-dashboard.json
      kubernetes-chaiyd-dashboard:
        file: dashboards/kubernetes-chaiyd-dashboard.json
      kubernetes-vuxuanlai266-dashboard:
        file: dashboards/kubernetes-vuxuanlai266-dashboard.json

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/default

